--- 
before_install: 
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
deploy: 
  - 
    api_key: 
      secure: AjwbRLStNJZb9hAOLfRLK85KlFo2q2Dr1NKCoDS4elek1nqSiOjL1hH0kDgUMx/PJqQVnFU8tbJPL30t9Pj7jcJhp0LhbbPipQE3TCSpafTneSEbdz5HT+OdghWCZhUhfs07wGNTFUwcAO4WBZ7wv1AnfdfogHdA5RMdykiIl38=
    file: 
      - ckan.exe
    provider: releases
    true: 
      all_branches: true
      mono: "3.10.0"
      repo: KSP-CKAN/CKAN
      tags: true
  - 
    access_key_id: AKIAI5JWAEFPFK6GH3XA
    acl: public_read
    all_branches: true
    bucket: ckan-travis
    local-dir: uploads
    provider: s3
    secret_access_key: 
      secure: b0PPlD7auqysK2LHA8N1US03dE/VKH2rOTwIqpIh50l/gURuXEl7Nd8S7qlf2dpEmz+8D5pIWD+J9scfrdD8Uuakhi3sQbqcV26UiR6+Ye06eGQfmIzqzAECt2naqEy7VJ/xrqq5aaaf8QhcOQMba3qVvwDSzkB2fJeh7+D6EY8=
    skip_cleanup: true
    true: 
      repo: KSP-CKAN/CKAN
install: 
  - "sudo apt-get install mono-devel nunit-console libtest-most-perl libipc-system-simple-perl"
  - "mozroots --import --ask-remove"
language: csharp
mono: 
  - latest
  - "3.10.0"
  - "3.2.8"
notifications: 
  irc:
    channels: 
      - "irc.esper.net#ckan-ci"
    template: 
      - "%{repository_name}#%{build_number} (%{branch} - %{commit} : %{author}): %{message}"
      - "Change view : %{compare_url}"
      - "Build details : %{build_url}"
    use_notice: true
script: 
  - bin/build
  - "nunit-console --exclude=FlakyNetwork build/Tests/bin/Debug/CKAN.Tests.dll"
  - prove
